# Generated by Django 4.0.3 on 2022-03-18 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=13, null=True)),
                ('email', models.EmailField(max_length=25, null=True, verbose_name='email address')),
                ('date_of_birthday', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Managers',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('created', models.DateField(null=True)),
                ('limit', models.DateField(null=True)),
                ('product', models.CharField(max_length=400)),
                ('number', models.IntegerField()),
                ('price', models.IntegerField()),
                ('percent', models.IntegerField()),
                ('status_order', models.CharField(choices=[('шт', 'шт'), ('усл', 'усл')], default='шт', max_length=20)),
                ('product1', models.CharField(max_length=400)),
                ('number1', models.IntegerField()),
                ('price1', models.PositiveIntegerField()),
                ('percent1', models.IntegerField()),
                ('status_order1', models.CharField(choices=[('шт', 'шт'), ('усл', 'усл')], default='шт', max_length=100)),
                ('product2', models.CharField(max_length=400)),
                ('number2', models.IntegerField()),
                ('price2', models.PositiveIntegerField()),
                ('percent2', models.IntegerField()),
                ('status_order2', models.CharField(choices=[('шт', 'шт'), ('усл', 'усл')], default='шт', max_length=100)),
                ('product3', models.CharField(max_length=400)),
                ('number3', models.IntegerField()),
                ('price3', models.PositiveIntegerField()),
                ('percent3', models.IntegerField()),
                ('status_order3', models.CharField(choices=[('шт', 'шт'), ('усл', 'усл')], default='шт', max_length=100)),
                ('product4', models.CharField(max_length=400)),
                ('number4', models.IntegerField()),
                ('price4', models.PositiveIntegerField()),
                ('percent4', models.IntegerField()),
                ('status_order4', models.CharField(choices=[('шт', 'шт'), ('усл', 'усл')], default='шт', max_length=100)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
