# Generated by Django 4.0.3 on 2022-03-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0002_alter_ordermodel_number1_alter_ordermodel_number2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status_order',
            field=models.CharField(blank=True, choices=[('шт', 'шт'), ('усл', 'усл')], default='шт', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status_order2',
            field=models.CharField(blank=True, choices=[('шт', 'шт'), ('усл', 'усл')], default='шт', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status_order3',
            field=models.CharField(blank=True, choices=[('шт', 'шт'), ('усл', 'усл')], default='шт', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status_order4',
            field=models.CharField(blank=True, choices=[('шт', 'шт'), ('усл', 'усл')], default='шт', max_length=100, null=True),
        ),
    ]
