# Generated by Django 4.0.3 on 2022-03-20 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0004_managermodel_groups_managermodel_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='manager',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
